#!/usr/bin/env php

<?php

// Capturamos la ip del cliente que ejecuta el comando
$ip = explode( ' ', $_SERVER['SSH_CLIENT'] )[0];
define( 'IP', $ip );

// Definimos las credenciales de MySQL
$path = __DIR__ . '/polaris';
define( 'PATH', $path );
define( 'PATH_BACKUP', PATH . '/storage/app/backup/' );

// Incluímos Polaris
include( "{$path}/polaris.php" );

// Función para mostrar los Backups de Polaris
function version_control()
{
  // Escaneamos los backups del directorio raíz
  $arr = scandir( PATH . '/storage/app/backup/' );
  $num_files = count( $arr ) - 2;

  // Iteramos los ficheros
  foreach ( $arr as $key => $backup )
  {
    // Si son directorios de sistema, nos los saltamos
    if( in_array( $backup, [ '.', '..' ] ) )
      continue;

    // Capturamos las variables de formato
    $db_name = explode( '_', $backup )[0];
    $filemtime = date( "d/m/y H:i:s", @filemtime( PATH . '/storage/app/backup/' . $backup ) );

    // Calculamos el nombre del hash a mostrar
    $backup = str_replace( array( $db_name, '.sql', '_' ), '', $backup );
    $backup = substr( $backup, 0, 6 );

    $key_buffer = ( $key - 2 );

    // Formato ASCII
    if( ( $key - 2 ) == 0 )
      $chr = "\u{250C} {$key_buffer} - ";
    elseif( ( $key - 2 ) === $num_files - 1 )
      $chr = "\u{2514} {$key_buffer}*- ";
    else
      $chr = "\u{251C} {$key_buffer} - ";

    // Imprimimos los directorios
    echo $chr . $backup . ' - ' . $filemtime . ' - ' . $db_name . "\n";
  }
}

// Función para crear un backup antes de restaurar una versión
function create_version( $db_name )
{
  // Inicializamos el MySQL y realizamos el backup
  $db = new pl_model( $db_name );
  $backup_file_name = $db->pl_migration_backup_database( DB_SERVER, DB_USER, DB_PASSWORD, $db_name, PATH_BACKUP, IP );

  // Retornamos el nombre del fichero SQL que almacena el Backup
  return $backup_file_name;
}

// Función para mostrar las bases de datos de MySQL
function show_databases()
{
  // Ejecutamos el comando
  $cmd = 'mysql -u ' . DB_USER . " -p'" . DB_PASSWORD . "' --skip-column-names -e 'SHOW DATABASES;'";
  $output = shell_exec($cmd);

  // Convierte la salida en un array y movemos el puntero al primer elemento
  $databases = explode( "\n", trim( $output ) );
  array_shift( $databases );
  $db_count = count( $databases );

  // Imprimimos el array de bases de datos
  foreach ( $databases as $key => $database )
  {

    // Formato ASCII
    if( ( $key ) == 0 )
      $chr = "\u{250C} {$key} - ";
    elseif( ( $key ) === $db_count - 1 )
      $chr = "\u{2514} {$key} - ";
    else
      $chr = "\u{251C} {$key} - ";

    // Imprimimos los datos de la DB
    echo $chr . $database . "\n";
  }

  return $databases;
}

// Función para restaurar una versión específica de MySQL
function restore_version( $id )
{
  // Definimos la ruta de los backups
  $db_name = '';

  // Analizamos los backups
  $arr = scandir( PATH_BACKUP );
  foreach ( $arr as $item )
  {
    if( count( $arr ) == 0 )
    {
      echo "No backups found in: " . PATH_BACKUP . '\n';
      break;
    }

    if( in_array( $item, [ '..', '.' ] ) )
      continue;

    // Sacamos el nombre de la base de datos y el hash del backup
    $arr_backup = explode( '_', $item );
    $db_name = $arr_backup[0];
    $backup_id = $arr_backup[1];

    // Restauramos
    if( strlen( $id ) === 6 && substr( $id, 0, 6 ) === substr( $backup_id, 0, 6 ) )
    {

      try {
        $cmd = 'mysql -u ' . DB_USER . ' -p' . "'" . DB_PASSWORD . "'" . ' ' . $db_name . ' < ' . PATH_BACKUP . '/' . $item;

        // Creamos un backup de la versión de MySQL anterior a la restauración
        exec( $cmd );
        create_version( $db_name, PATH_BACKUP );

        print "Database restored\n";
      } catch ( \Exception $e ) {}

    }
  }
}

if( isset( $argv[1] ) )
{
  switch ( $argv[1] ) {
    case 'restore':
      if( isset( $argv[2] ) )
        restore_version( $argv[2] );
      else
        print "Backup ID required\n";
      break;

    case 'show':
      show_databases();
      break;

    case 'create':
      $databases = show_databases();
      
      // Input para seleccionar la base de datos a hacer backup
      echo "Select the database to backup > ";
      $database_id = trim( fgets( STDIN ) );

      // Creamos el backup según el índice insertado
      create_version( $databases[ $database_id ] );
      break;

    default:
      break;
  }
}
else
{
  version_control();
}

?>